//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByteShop.Domain.DomainMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceValidationErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceValidationErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByteShop.Domain.DomainMessages.ResourceValidationErrorMessage", typeof(ResourceValidationErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria inexistente..
        /// </summary>
        public static string CATEGORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CATEGORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório..
        /// </summary>
        public static string CATEGORY_NAME_EMPTY {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome suporta apenas 50 caracteres..
        /// </summary>
        public static string CATEGORY_NAME_MAXIMUMLENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_MAXIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatorio..
        /// </summary>
        public static string EMPTY_CPF {
            get {
                return ResourceManager.GetString("EMPTY_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email está vazio..
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo usuario é obrigatorio..
        /// </summary>
        public static string EMPTY_USERNAME {
            get {
                return ResourceManager.GetString("EMPTY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas as seguintes extensões são permitidas: webp, jpe, jpg, jpeg..
        /// </summary>
        public static string IMAGE_EXTENSION {
            get {
                return ResourceManager.GetString("IMAGE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem está incorreta. verifique os campos de base64 e extension..
        /// </summary>
        public static string INCORRECT_IMAGE {
            get {
                return ResourceManager.GetString("INCORRECT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta solicitação contém base64 inválida..
        /// </summary>
        public static string INVALID_BASE64 {
            get {
                return ResourceManager.GetString("INVALID_BASE64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado não é valido..
        /// </summary>
        public static string INVALID_CPF {
            get {
                return ResourceManager.GetString("INVALID_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email está invalido..
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho maximo para uma imagem é de 350kb..
        /// </summary>
        public static string MAX_IMAGE_SIZE {
            get {
                return ResourceManager.GetString("MAX_IMAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É permitido apenas 5 imagens..
        /// </summary>
        public static string MAXIMUM_AMOUNT_OF_IMAGES {
            get {
                return ResourceManager.GetString("MAXIMUM_AMOUNT_OF_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessario ter uma imagem principal..
        /// </summary>
        public static string MUST_HAVE_A_MAIN_IMAGE {
            get {
                return ResourceManager.GetString("MUST_HAVE_A_MAIN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria pai não existe.
        /// </summary>
        public static string PARENT_CATEGORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("PARENT_CATEGORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo marca é obrigatório..
        /// </summary>
        public static string PRODUCT_BRAND_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_BRAND_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo marca suporta apenas 60 caracteres..
        /// </summary>
        public static string PRODUCT_BRAND_MAXIMUMLENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_BRAND_MAXIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo descrição é obrigatório..
        /// </summary>
        public static string PRODUCT_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto inexistente..
        /// </summary>
        public static string PRODUCT_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo altura deve ser maior que zero..
        /// </summary>
        public static string PRODUCT_HEIGHT_LESS_OR_EQUAL_TO_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_HEIGHT_LESS_OR_EQUAL_TO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo comprimento deve ser maior que zero..
        /// </summary>
        public static string PRODUCT_LENGTH_LESS_OR_EQUAL_TO_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_LENGTH_LESS_OR_EQUAL_TO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório..
        /// </summary>
        public static string PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome suporta apenas 60 caracteres..
        /// </summary>
        public static string PRODUCT_NAME_MAXIMUMLENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_MAXIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo SKU é obrigatório..
        /// </summary>
        public static string PRODUCT_SKU_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_SKU_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo peso deve ser maior que zero..
        /// </summary>
        public static string PRODUCT_WEIGHT_LESS_OR_EQUAL_TO_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_WEIGHT_LESS_OR_EQUAL_TO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo largura deve ser maior que zero..
        /// </summary>
        public static string PRODUCT_WIDTH_LESS_OR_EQUAL_TO_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_WIDTH_LESS_OR_EQUAL_TO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao envia imagem principal. envie como base64 ou link.
        /// </summary>
        public static string UPDATE_PRODUCT_WITH_INVALID_MAIN_IMAGE {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_WITH_INVALID_MAIN_IMAGE", resourceCulture);
            }
        }
    }
}
